### ISSUE TITLE
I got the error "Invalid token" when submitting a POST request to route registered from a file.

### ISSUE THREAD

**Issue by meotimdihia** [fastify/csrf-protection#107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I got the error "Invalid token" when submitting a POST request to route registered from a file.
```js
fastify.register(indexPost);
```

### This is an example:
https://codesandbox.io/s/fastify-csrf-protection-typescript-ngzpec?file=/index.ts:0-1634
You will see the error when you click submit.

### The screenshot:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/300961/187935543-2cec7841-f0c2-4846-b703-479741c7ff6e.png">

**Comment by mcollina** [comment]
Check out https://github.com/fastify/csrf-protection/pull/108. I've added your code as an example and fixed it. Thanks for spotting the hole in our docs.
