### ISSUE TITLE
Invalid csrf token from cookie value

### ISSUE THREAD

**Issue by Poiuytrezay1** [fastify/csrf-protection#118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

6.0.0

### Node.js version

16.13.2

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

I get the error "Invalid csrf token" when submitting a request with an XSRF-TOKEN header containing the value of the signed _csrf cookie.

### Steps to Reproduce

Using nest as a framework. I send the CSRF token from login, and add a XSRF-TOKEN header to requests:

In main.ts:
```
  const adapter = new FastifyAdapter({ logger: true });
  const fastifyInstance = adapter.getInstance();
  const options: NestApplicationOptions = {};
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, adapter, options);

  ...

  await app.register(fastifyCookie, {
    secret: configService.get('COOKIE_SECRET')
  });
  await app.register(fastifyCsrf, {
    cookieOpts: { signed: true },
    getToken: (req: FastifyRequest) => {
      return <string>req.headers['xsrf-token']; // for some reasons I have a type error error
    }
  });

  // Add hook
  fastifyInstance.addHook('onRequest', (request: FastifyRequest, reply: FastifyReply, done: (err?: Error) => void) => {
    if (request.url !== '/api/auth/login' && request.url !== '/api/auth/register') {
      fastifyInstance.csrfProtection(request, reply, done);
    } else {
      done();
    }
  });
```

In my auth controller (login endpoint):
```
  @Post('login')
  public async login(...): Promise<...> {
    ...

    const token = response.generateCsrf();
    response.status(HttpStatus.OK).send(ouput);
  }
```

On any endpoint, _after login,_ I send a request with headers:
```
...
Cookie: Authorization=YYY; _csrf=XXX // results from login request
XSRF-TOKEN: XXX // taken from cookie _csrf value
```

And I'm returned with:
```
{
    "statusCode": 403,
    "code": "FST_CSRF_INVALID_TOKEN",
    "error": "Forbidden",
    "message": "Invalid csrf token"
}
```

### Expected Behavior

There should be no error, the request should succeed (unless there is something I didn't understand?)

**Comment by mcollina** [comment]
Thanks for reporting. We do not have the resources to support Nest.js users. Please refer to the Nest [Discord](discord.gg/NestJS) channel (support) for such questions.

**Comment by mcollina** [comment]
We'll be happy to help with an issue using plain Fastify.

**Comment by Poiuytrezay1** [comment]
I think this issue concerns the code from plain fastify, not nest. It fails on the token validation. I could remove all nest code, and it would have the same problem:

The token is generated using the **generateCsrf** method from @fastify/csrf-protection which calls the method from @fastify/cookie to sign it, and the method from @fastify/csrf to generate the secret. The "nest" part handles the request, and it correctly returns the Cookie header.

The token is verified by the **csrfProtection** method from @fastify/csrf-protection which calls the verify method from @fastify/csrf => and this is what fails. The values in debug are the correct ones (i.e. the unsigned cookie as the secret, and cookie value as the token). The hook is correctly called, with the values given in the request header (e.g. the cookie and the XSRF-TOKEN header).

I think this is a problem between the cookie sign and the method to validate the csrf token not being the same.

**Comment by Poiuytrezay1** [comment]
I solved my problem alone, thank you.

**Comment by jsumners** [comment]
> I solved my problem alone, thank you.

Thank you for posting your solution for others to learn from.
