### ISSUE TITLE
`req.body` is undefined

### ISSUE THREAD

**Issue by williamputraintan** [fastify/csrf-protection#130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.13.0

### Plugin version

6.1.0

### Node.js version

18.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13

### Description

Hello,

I am trying to put the csrf token to be part of the input form (Similar to [this](https://github.com/fastify/csrf-protection/issues/9)), but it seems that the getToken() function fail in getting the token out from the body.

From the [docs](https://github.com/fastify/csrf-protection#fastifycsrfprotectionrequest-reply-next), it seems to be possible to do so.

I tried to print the body and it seems to have an `undefined` value.

```
      fastify.register(fastifyCsrfProtection, {
        sessionPlugin: "@fastify/secure-session",
        getToken: (req) => {
          console.log("the body", req.body);
          return "TEMP_TOKEN";
        },
      });
```

I am wondering if the middleware mentioned [here](https://github.com/nestjs/nest/issues/10466#issuecomment-1292728585) is relevant to the undefined value.

### Steps to Reproduce

1. Setup a Fastify Server with the `fastifyCsrfProtection` enabled with the default config of `getToken()`
2. From the FE, submit a <form> that includes `_csrf` token as a hidden input.
3. Submit the form and invalid `csrf` token error was thrown (InternalServerError), same token works if it is put in the header.

### Expected Behavior

No Invalid csrf-token error thrown.

**Comment by mcollina** [comment]
How are you configuring your routes? You'd need to use the `preHandler` hook to be able to access the body of the request (in the README we have onRequest).

**Comment by williamputraintan** [comment]
Ah right, I missed this on the README (I set it up with `onRequest`). Thanks for pointing this out!
